name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install
        run: yarn

      - name: Build
        run: yarn webpack

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        env:
          REACT_APP_BACKEND_URL: http://localhost:3200
        with:
          branch: gh-pages
          folder: dist
